/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avishkar;
import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
/**
 *
 * @author Avishkar
 */
public class login_page extends javax.swing.JFrame implements ActionListener{

    JLabel l1,l2,l3;
        JTextField t1,t2;
        JButton b;
    /**e3
     * Creates new form login_page
     */    public login_page() {

               
    l1=new JLabel("USERNAME:-");
        l1.setBounds(500,300,100,30);
        t1=new JTextField();
        t1.setBounds(600,300,200,30);
        l2=new JLabel("PASSWORD:-");
        l2.setBounds(500,350,100,30);
        t2=new JTextField();
        t2.setBounds(600,350,200, 30);
        l3=new JLabel("Forgot password");
        l3.setBounds(600,400,300,30);
        l3.setBackground(Color.blue);
        
        JPanel buttonpanel=new JPanel();
       
        b=new JButton("LOGIN");
        b.setBounds(600,450,100,30);
  buttonpanel.add(b);
  buttonpanel.setBackground(Color.red);
        //add(f
      
        add(l1);
        add(t1);
        add(l2);
        add(t2);
        add(l3);
       add(b);
        //(buttonpanel);
      //b.addActionListener( this);
   b.addActionListener(this);
        initComponents();
    }
@Override
     public void actionPerformed(ActionEvent e)
{
    String uname=t1.getText();
    String passs=t2.getText();
    try
    {
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
        PreparedStatement stmt=conn.prepareStatement("SELECT * FROM loginn WHERE user=? AND pass=?");
        stmt.setString(1, uname);
        stmt.setString(2, passs);
        ResultSet rst=stmt.executeQuery();
        if(rst.next())
        {
            JOptionPane.showMessageDialog(this, "connection successfully");
            welcome w1=new welcome();
            w1.setVisible(true);
        }
        else
        {
            System.out.println("error while connecting databasd");
        }
        conn.close();
    }
    catch(SQLException e1)
    {
      JOptionPane.showMessageDialog(this, "COONECTION ERROR"   );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
